services:
  app:      # app 이하 코드를 도커 이미지 빌드 후 추가!
    image: team-mate-app:local
    container_name: team-mate-app-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - team_mate-mysql
    restart: unless-stopped

  team_mate-mysql:
    image: mysql:8.0.43
    container_name: team_mate-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: team_mate_root
      MYSQL_DATABASE: team_mate_db
      MYSQL_USER: team_mate
      MYSQL_PASSWORD: team_mate_pw
      TZ: Asia/Seoul
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3307:3306"
    volumes:
      - ./_vol/mysql:/var/lib/mysql