spring:
  profiles:
    active: dev # OR prod

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      max-file-size: 10MB      # 파일 하나당 최대 크기
      max-request-size: 50MB   # 한 번 요청에 보낼 수 있는 전체 크기